### ISSUE TITLE
Returns to ZERO

### ISSUE THREAD

**Issue by phoniclynx** [heyajohnny/cryptoinfo#3]
When HA reboots the script makes the sensor value "0"... making the graphs that I am outputting using a template unreadable because the values range around the 4000 marks and the graph plummets to 0 making the variability of the graph unnoticeable

**Comment by heyajohnny** [comment]
I've just pushed an update that should fix it. Beware that you need to delete the history. The easiest way is to just delete the database file and restart HA. After that, it should be working flawlessly.

**Comment by phoniclynx** [comment]
Where do I find the database file?

**Comment by heyajohnny** [comment]
It's in the main directory of Home Assistant. It's called 'home-assistant_v2.db'

**Comment by phoniclynx** [comment]
That didn't seem to fix the issue... I convert it using a template but the sensor when it starts is set to unknown.. then before it grabs the data from coingecko it sets a coin value to $0.00 then grabs each one, by one and sets is value. ... it's the $0.00 which breaks the graph.
So whenever you reset HA after an update of configurations.yaml or upgrade of the software it sets all the values to 0 when I think it should be set to "unknown" or something so that the graphs don't get mangled.

**Comment by heyajohnny** [comment]
That is very strange... I can't reproduce your issue. When I restart my HA it sets the value to 'Unknown' and then gets the right value. Maybe if you upgrade your HA to the latest version it will be fixed. Or it has something to do with some system variables... I really don't know how I can reproduce / fix this.

**Comment by phoniclynx** [comment]
I'll show you the code I have:
- platform: cryptoinfo
cryptocurrency_name: "bitcoin"
currency_name: "usd"
update_frequency: 1
- platform: cryptoinfo
cryptocurrency_name: "bitcoin"
currency_name: "aud"
update_frequency: 1
- platform: cryptoinfo

- platform: template
sensors:
crypto_bitcoin_owned:
friendly_name: "Bitcoin Owned"
unit_of_measurement: '$'
value_template: "{{ (states('sensor.cryptoinfo_bitcoin_aud')|float *
0.12345) | round(2) }}"

**Comment by heyajohnny** [comment]
Please try this for your template sensor:
```
  - platform: template
    sensors:
      crypto_bitcoin_owned:
        friendly_name: "Bitcoin Owned"
        unit_of_measurement: '$'
        value_template: >-
          {% if not is_state('sensor.cryptoinfo_bitcoin_aud', 'unknown') %}
            {{ (states('sensor.cryptoinfo_bitcoin_aud')|float *0.12345) | round(2) }}
          {%endif %}
```

**Comment by phoniclynx** [comment]
ok.. that fixes that problem but creates a slightly different one. I have
14 coins that I'm grabbing the details from and then it totals them all up.
But because it takes time to get all the coins together it cripples that
graph as it goes to 0 and gradually gets more and more as it collects the
prices.
How would I fix this template to reflect that?:
crypto_total_owned:
friendly_name: "Total Coin Owned"
unit_of_measurement: '$'
value_template: "{{ ((states('sensor.crypto_bitcoin_owned')|float) +
(states('sensor.crypto_ethereum_owned')|float) +
(states('sensor.crypto_aave_owned')|float) +
(states('sensor.crypto_cardano_owned')|float) +
(states('sensor.crypto_kyber_owned')|float) +
(states('sensor.crypto_chainlink_owned')|float) +
(states('sensor.crypto_vechainthor_owned')|float) +
(states('sensor.crypto_republic_protocol_owned')|float) +
(states('sensor.crypto_monero_owned')|float) +
(states('sensor.crypto_loopring_owned')|float) +
(states('sensor.crypto_verge_owned')|float) +
(states('sensor.crypto_binancecoin_owned')|float) +
(states('sensor.crypto_kava_owned')|float) +
(states('sensor.crypto_enjincoin_owned')|float) +
(states('sensor.crypto_neo_owned')|float)) | round(2) }}"

**Comment by heyajohnny** [comment]
Did the code above fixed your issue?

**Comment by phoniclynx** [comment]
yes

**Comment by heyajohnny** [comment]
Oke :) I'm closing the issue.
